---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: flrmh/app-sparta:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://mongo:27017/posts
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["node", "seeds/seed.js"]
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
  apiVersion: v1
  kind: Service
  metadata:
     name: app-svc
     namespace: default
  spec:
    ports:
    - nodePort: 30002
      port: 3000

      targetPort: 3000

    selector: 
      app: node-app

    type: NodePort